version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: interview
      POSTGRES_PASSWORD: password
      POSTGRES_DB: interview_production
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/var/www/interview_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://interview:password@db/interview_production

